---
# name of the log file that should contain backup process logs. ["/var/log/ansible.log"]
nextcloud_backup_logfile: /var/log/ansible.log
# nextcloud_backup_user: Name of the user who will be granted ownerships of data backups. ["nextcloud"]
nextcloud_backup_user: nextcloud
# nextcloud_backup_group: Name of the group who will be granted ownerships of data backups. ["nextcloud"]
nextcloud_backup_group: nextcloud

# database configuration
nextcloud_db_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38376434616463336334373730323164393361386466336439616335303935666335326234666139
  3962343362373138306134636230643063313339366664640a663939346364383839623864336130
  36353666653866343166643834363436393134333135613366653237326166363836626438633363
  3736386165383737370a623863646539393530663838313137613831306238336365613164313666
  64656461636634613862353038373837633631656661343463656165636233346265366532383064
  34643265306130616466303566373537626464643036383562353866643137353961303935643532
  65616164643732316264656661313661636331626133373237353439386465613236623861633631
  66383739373336313630

# nextcloud_admin: Initial credentials for the admin account. [provide during one-time setup]
# nextcloud_admin.password: Initial password for the nextcloud admin account.
# nextcloud_admin.username: Initial username for the nextcloud admin account.
# nextcloud_admin:

# nextcloud_backup_path: Root directory in which to store backups. ["{{ nextcloud_path }}/backups."]
# nextcloud_backup_path:

# nextcloud_data_path: Base path for instance-specific data (apps, config, and files). ["{{ nextcloud_path }}/data"]
# nextcloud_data_path:

# nextcloud_db: Initial database configuration. This is ignored after Nextcloud's one-time setup has been completed. [provide DB during one-time setup]
# nextcloud_db.host: Database host server name.
# nextcloud_db.name: Name of the Nextcloud database. ["nextcloud"]
# nextcloud_db.password: Password to use when connecting to the database.
# nextcloud_db.port: Port number to use when connecting to the database. [default is driver specific]
# nextcloud_db.table_prefix: Prefix for the Nextcloud tables in the database. ["oc"]
# nextcloud_db.type: Type of database (mysql, pgsql, sqlite3). The corresponding PHP driver must be installed.
# nextcloud_db.username: Username to use when connecting to the database.
# nextcloud_db:

nextcloud_imagick_version: 3.6*
nextcloud_libmagickcore_extra_version: 8:6.9*

# nextcloud_maintenance_mode: whether the server should be in maintenance mode or not. [false]
nextcloud_maintenance_mode: false

# nextcloud_path: Root filesystem path to use for nextcloud resources. ["/var/lib/nextcloud"]
nextcloud_path: /var/lib/nextcloud

# nextcloud_mail: Configuration options for Nextcloud notifications and password resets. Either 'null' or a dictionary of options. [null]
# nextcloud_mail.domain: Domain to use when sending mail. [Nextcloud application domain]
# nextcloud_mail.enabled: Whether outgoing mail will be configured or not. [false]
# nextcloud_mail.from_address: FROM address that overrides the built-in sharing-noreply and lostpassword-noreply FROM addresses.
# nextcloud_mail.smtp_auth: SMTP authentication options. Either null (for no auth), or a dictionary with a 'username' and 'password'. [null]
# nextcloud_mail.smtp_auth.password: Password for authenticating to the SMTP server.
# nextcloud_mail.smtp_auth.username: Username for authenticating to the SMTP server.
# nextcloud_mail.smtp_host: Name of your mail server host. This may contain multiple hosts separated by a semicolon. [Required]
# nextcloud_mail.smtp_port: Port to use for sending mail. [25]
# nextcloud_mail.smtp_use_tls: Whether to connect to the SMTP server using SSL/TLS. [true]
# nextcloud_mail:

# nextcloud_version: Version number of Nextcloud to install. ["25.0.8"]
nextcloud_version: 25.0.8
