---
- name: Verify required variables are set
  block:
    - name: Assert name is set
      ansible.builtin.assert:
        fail_msg: "'name' required for managed apache module"
        that:
          - name is defined
    - name: State is valid
      ansible.builtin.assert:
        fail_msg: "Invalid 'state' value (must be 'absent' or 'present'). (Was: {{ state }})"
        that:
          - state == 'absent' or state == 'present'

- name: "Manage Apache module: {{ name }}"
  community.general.apache2_module:
    name: "{{ name }}"
    state: "{{ state }}"
