# Probably should use these roles: https://github.com/sys0dm1n/ansible-ubuntu-desktop
# Visual Studio Code role from: https://github.com/gantsign/ansible-role-visual-studio-code

- hosts: localhost
  become: true
  connection: local
  roles:
    - role: common
    - role: elastic-agent
    - role: qemu-agent
    - role: desktop
    - role: dbeaver
    - role: discord
    - role: insync
    - role: nodejs
    - role: spotify
    - role: visual-studio-code
      users:
        - username: '{{ desktop_username }}'
          visual_studio_code_extensions:
            - johnpapa.vscode-peacock
            - ryanolsonx.solarized
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "diffEditor.ignoreTrimWhitespace": false,
            "terminal.integrated.allowChords": false,
            "workbench.colorTheme": "Solarized Dark+",
            "editor.tabSize": 2,
            "files.autoSave": "onFocusChange"
          }

    - role: zettlr
  tasks:
  # add lockbox mounts
  #- name: Copy encrypted credentials
  #  ansible.builtin.copy:
  #    src: '{{ playbook_dir }}/files/lockbox_credentials'
  #    dest: /root/.smbcredentials_lockbox
  #    owner: root
  #    group: root
  #    mode: '0600'
  #- import_tasks: tasks/add-cifs-mount.yml
  #  vars:
  #    credentials_file: /root/.smbcredentials_lockbox
  #    path: /mnt/lockbox/sean
  #    src: //lockbox.local/sean
  #- import_tasks: tasks/add-cifs-mount.yml
  #  vars:
  #    credentials_file: /root/.smbcredentials_lockbox
  #    path: /mnt/lockbox/shared
  #    src: //lockbox.local/shared
  #- import_tasks: tasks/add-cifs-mount.yml
  #  vars:
  #    credentials_file: /root/.smbcredentials_lockbox
  #    path: /mnt/lockbox/google-drive
  #    src: //lockbox.local/google-drive
  #- import_tasks: tasks/add-cifs-mount.yml
  #  vars:
  #    credentials_file: /root/.smbcredentials_lockbox
  #    path: /mnt/lockbox/usb-drive
  #    src: //lockbox.local/usb-drive
 
