# Probably should use these roles: https://github.com/sys0dm1n/ansible-ubuntu-desktop

- hosts: localhost
  become: true
  roles:
    # from: https://github.com/gantsign/ansible-role-visual-studio-code
    - role: visual-studio-code
    - role: zettlr
  tasks:
  - name: Install packages needed for installation
    apt: name={{item}}
    with_items:
      - software-properties-common
      - apt-transport-https
      - wget
  # install insync
  - name: Add insync apt key
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: ACCAF35C
  - name: Add insync apt repository
    ansible.builtin.apt_repository:
      repo: deb http://apt.insync.io/ubuntu focal non-free contrib
      state: present
  - name: Update repositories cache and install "insync" package
    apt:
      name: insync
      update_cache: yes

  # add lockbox mounts
  - name: Copy encrypted credentials
    ansible.builtin.copy:
      src: '{{ playbook_dir }}/files/lockbox_credentials'
      dest: /root/.smbcredentials_lockbox
      owner: root
      group: root
      mode: '0600'
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/sean
      src: //lockbox.local/sean
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/shared
      src: //lockbox.local/shared
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/google-drive
      src: //lockbox.local/google-drive
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/usb-drive
      src: //lockbox.local/usb-drive
  