# Probably should use these roles: https://github.com/sys0dm1n/ansible-ubuntu-desktop

- hosts: localhost
  become: true
  vars:
    zettlr_download_url: https://github.com/Zettlr/Zettlr/releases/download/v2.2.4/Zettlr-2.2.4-amd64.deb
  roles:
    # from: https://github.com/gantsign/ansible-role-visual-studio-code
    - role: visual-studio-code
  tasks:
  - name: Install packages needed for installation
    apt: name={{item}}
    with_items:
      - software-properties-common
      - apt-transport-https
      - wget

  # install Zettlr
  - name: Install a .deb package from the internet
    apt:
      deb: "{{ zettlr_download_url }}"

  # add lockbox mounts
  - name: Copy encrypted credentials
    ansible.builtin.copy:
      src: '{{ playbook_dir }}/files/lockbox_credentials'
      dest: /root/.smbcredentials_lockbox
      owner: root
      group: root
      mode: '0600'
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/sean
      src: //lockbox.local/sean
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/shared
      src: //lockbox.local/shared
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/google-drive
      src: //lockbox.local/google-drive
  - include: tasks/add-cifs-mount.yml
    vars:
      credentials_file: /root/.smbcredentials_lockbox
      path: /mnt/lockbox/usb-drive
      src: //lockbox.local/usb-drive
  