collections:
- name: ansible.posix
  version: '>=1.5.1'
- name: community.general
  version: '>=6.4.0'  
- name: community.mysql
  version: '>=3.6.0'
- name: devsec.hardening
  version: '>=8.6.0'

roles:
- name: geerlingguy.apache
  version: '3.3.0'
- name: stefangweichinger.ansible_rclone
  version: '0.1.2'
