---
- name: Install common CLI and support utilities
  apt: 
    pkg: 
      - apt-transport-https
      - curl
      - software-properties-common
      - wget
    state: present
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"