all:
  children:
    coder_servers:
      hosts:
        coder-[00:99]:
        coder-blue:
        coder-green:
    logitech_media_servers:
      hosts:
        lms-[00:99]:
    nas_servers:
      hosts:
        nfs:
        nfs-[00:99]:
        nas-[00:99]:
    net_ingress_servers:
      hosts:
        net-ingress-[02:99]:
        net-ingress-blue:
        net-ingress-green:
    nextcloud_servers:
      hosts:
        nextcloud-blue:
        nextcloud-green:
        nextcloud-[00:99]:
    proxmox_nodes:
      hosts:
        192.168.68.11:
          ansible_connection: ssh
          ansible_user: ansible
    servers:
      children:
        logitech_media_servers:
        nas_servers:
        nextcloud_servers:
        vrising_servers:
    vrising_servers:
      hosts:
        vrising-[00:99]:
      vars:
        elastic_agent_enrollment_token: MUST_BE_SET
    workstations:
      hosts:
        patchwork-blue:
        patchwork-green:
      vars:
        elastic_agent_enrollment_token: MUST_BE_SET
  vars:
    ansible_connection: local
