all:
  children:
    k3s:
      children:
        k3s_agents:
        k3s_servers:
    k3s_agents:
      hosts:
        k3s-01:
    k3s_servers:
      hosts:
        k3s-00:
    nas_servers:
      hosts:
        nfs:
        nfs-[00:99]:
        nas-[00:99]:
    nextcloud_servers:
      hosts:
        nextcloud-blue:
        nextcloud-green:
        nextcloud-[00:99]:
    qemu:
      hosts:
        patchwork-blue:
        patchwork-green:
    servers:
      children:
        nas_servers:
        nextcloud_servers:
        vrising_servers:
    vrising_servers:
      hosts:
        vrising-[00:99]:
      vars:
        elastic_agent_enrollment_token: MUST_BE_SET
    workstations:
      hosts:
        patchwork-blue:
        patchwork-green:
      vars:
        elastic_agent_enrollment_token: MUST_BE_SET
  vars:
    ansible_connection: local
