- name: utility present
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: check mountpoint exists
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Mount network share
  ansible.posix.mount:
    src: "{{ src }}"
    path: "{{ path }}"
    fstype: cifs
    opts: 'auto,nobrl,user,uid=sean,gid=users,credentials={{ credentials_file }},iocharset=utf8,rw,noexec,nosuid,nodev'
    state: mounted