---
# install NoMachine
- name: Install the NoMachine .deb package
  apt:
    deb: "{{ no_machine_download_url }}"

# TODO: to enable USB forwarding, the nxusb module must be signed... this requires a physical console
# See: https://knowledgebase.nomachine.com/AR05O00929

# configure NoMachine server
- name: Template NoMachine server.cfg
  ansible.builtin.template:
    dest: '{{ no_machine_config_dir }}/server.cfg'
    group: nx
    mode: '0664'
    owner: nx
    src: files/usr/NX/etc/server.cfg