- name: Install restic via restic role
  ansible.builtin.include_role:
    name: restic
  vars:
    restic_repository:
      password: "{{ docker_backup_repository_password }}"
      path: "{{ docker_backup_repository }}"
      type: local
    restic_user: "{{ docker_backup_user | default(omit) }}"

- name: Copy scripts
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - "../templates/usr/local/bin/*"