- name: Create backup user
  when: "{{ docker_backup_user is defined }}"
  ansible.builtin.user:
    create_home: false
    group: "{{ docker_backup_user }}"
    name: "{{ docker_backup_user }}"
    password: "!"
    shell: /bin/false
    system: true
    uid: "{{ docker_backup_uid }}"

- name: Install restic via restic role
  ansible.builtin.include_role:
    name: restic
  vars:
    restic_repository:
      password: "{{ docker_backup_repository_password }}"
      path: "{{ docker_backup_repository }}"
      type: local
    restic_user: "{{ docker_backup_user | default(omit) }}"

- name: Copy scripts
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - "../templates/usr/local/bin/*"