- name: Copy scripts
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0744"
  with_fileglob:
    - "../templates/usr/local/bin/*"