# need to correctly invoke this to install restic 
#     - role: restic
#       vars:
#         restic_repository:
#           password: "{{ nextcloud_backup_password }}"
#           path: "{{ nextcloud_backup_path }}/repository"
#           type: local

- name: Copy scripts
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
  with_fileglob:
    - "../templates/usr/local/bin/*"