---
# install and configure application files

- name: Give webserver write permissions to required directories
  ansible.builtin.file:
    group: adm
    mode: "0770"
    owner: www-data
    path: "{{ item }}"
    recurse: true
    state: directory
  loop:
    - "{{ nextcloud_apps_path }}"
    - "{{ nextcloud_config_path }}"
    - "{{ nextcloud_files_path }}"

- name: Create symlinks to config for new version
  ansible.builtin.file:
    src: "{{ nextcloud_config_path }}"
    dest: "{{ nextcloud_current_version_path }}/config"
    group: www-data
    owner: root
    state: link

- name: Create symlink from document root to current version of nextcloud
  ansible.builtin.file:
    src: "{{ nextcloud_current_version_path }}"
    dest: "{{ nextcloud_document_root }}"
    group: adm
    owner: root
    state: link

- name: Give webserver write permissions to .htaccess
  ansible.builtin.file:
    group: www-data
    mode: "0775"
    owner: root
    path: "{{ nextcloud_document_root }}/.htaccess"
    state: file

- name: Determine if nextcloud has been configured already
  ansible.builtin.stat:
    path: "{{ nextcloud_config_file }}"
  register: nextcloud_config_stat

- name: Create 'CAN_INSTALL' marker if needed
  ansible.builtin.file:
    group: www-data
    mode: "0775"
    owner: root
    path: "{{ nextcloud_config_path }}/CAN_INSTALL"
    state: touch
  when: not nextcloud_config_stat.stat.exists
- name: Copy nextcloud auto-configuration template if needed
  ansible.builtin.template:
    src: autoconfig.php.j2
    dest: "{{ nextcloud_autoconfig_file }}"
    group: www-data
    mode: "0775"
    owner: root
  when: not nextcloud_config_stat.stat.exists

# update php settings

- name: Set php memory limit to recommendation of 512M
  ansible.builtin.lineinfile:
    path: "{{ __php_ini_path }}"
    regexp: "^memory_limit ="
    insertafter: "^; https://php.net/memory-limit"
    line: memory_limit = 512M
  notify: restart apache
