---
- name: Execute backup
  block:
    - name: Generate timestamp (YYYYMMDDTHHMMSS)
      ansible.builtin.set_fact:
        timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
    - name: "Ensure backup directory exists: {{ __nextcloud_paths.backup + '/' + timestamp }}"
      ansible.builtin.file:
        mode: "0700"
        owner: root
        group: root
        path: "{{ __nextcloud_paths.backup }}/{{ timestamp }}"
        state: directory
    - name: Create database backup
      community.mysql.mysql_db:
        state: dump
        name: "{{ nextcloud_db.name }}"
        target: "{{ __nextcloud_paths.backup }}/{{ timestamp }}/db.sql.gz"
