---
# download, verify, and unpack the nextcloud web application

- name: Ensure download directory exists
  ansible.builtin.file:
    group: adm
    mode: "0775"
    owner: root
    path: "{{ nextcloud_download_path }}"
    state: directory
- name: Ensure current version directory exists
  ansible.builtin.file:
    group: adm
    mode: "0775"
    owner: root
    path: "{{ nextcloud_current_version_path }}"
    state: directory

- name: Download nextcloud archive
  ansible.builtin.get_url:
    checksum: "sha256:{{ nextcloud_digest_url }}"
    dest: "{{ nextcloud_download_path }}/nextcloud-{{ nextcloud_version }}.tar.bz2"
    group: adm
    mode: "0664"
    owner: root
    url: "{{ nextcloud_download_url }}"
- name: Unarchive nextcloud
  ansible.builtin.unarchive:
    creates: "{{ nextcloud_current_version_path }}/index.php"
    dest: "{{ nextcloud_current_version_path }}"
    exclude:
      - nextcloud/config
    extra_opts: [--strip-components=1]
    group: www-data
    mode: "0755"
    owner: root
    src: "{{ nextcloud_download_path }}/nextcloud-{{ nextcloud_version }}.tar.bz2"
