---
# - name: Verify that Apache is installed
#   block:
#     - name: Query installed packages for "apache2"
#       changed_when: false
#       register: apt_result
#       ansible.builtin.command: apt list apache2
#     - name: Verify result is found
#       ansible.builtin.assert:
#         fail_msg: "Package 'apache2' could not be found"
#         that:
#           - apt_result.stdout | regex_search('(^|\n)apache2\/')

- name: Install Nextcloud
  tags: [nextcloud_install]
  block:
    - name: "Download nextcloud v{{ nextcloud_version }}"
      vars:
        checksum: "sha256:{{ nextcloud_digest_url }}"
        directory: "{{ nextcloud_download_path }}"
        filename: "nextcloud-{{ nextcloud_version }}.tar.bz2"
        # group: adm
        # mode: "0775"
        # owner: root
        url: "{{ nextcloud_download_url }}"
      ansible.builtin.include_role:
        name: fetch
        tasks_from: download.yml

# next thing to do is unarchive it here

- name: Download and unpack nextcloud
  ansible.builtin.import_tasks: download.yml

- name: Configure nextcloud application
  ansible.builtin.import_tasks: application.yml

- name: Manage backup and restore functions
  ansible.builtin.import_tasks: backup.yml
