---
- name: Install Nextcloud
  tags: [nextcloud_install]
  block:
    - name: "Download nextcloud v{{ nextcloud_version }}"
      vars:
        checksum: "sha256:{{ __nextcloud_digest_url }}"
        directory: "{{ __nextcloud_paths.work }}"
        filename: "nextcloud-{{ nextcloud_version }}.tar.bz2"
        mode: "0755"
        url: "{{ __nextcloud_download_url }}"
      ansible.builtin.include_role:
        name: fetch
        tasks_from: download.yml
    - name: Ensure current version directory exists
      ansible.builtin.file:
        mode: "0755"
        path: "{{ __nextcloud_current_version_path }}"
        state: directory
    - name: Unarchive nextcloud
      ansible.builtin.unarchive:
        creates: "{{ __nextcloud_current_version_path }}/index.php"
        dest: "{{ __nextcloud_current_version_path }}"
        exclude:
          - nextcloud/config
        extra_opts: [--strip-components=1]
        mode: "0755"
        src: "{{ __nextcloud_paths.work }}/nextcloud-{{ nextcloud_version }}.tar.bz2"

- name: Configure nextcloud application
  ansible.builtin.import_tasks: application.yml

- name: Manage backup and restore functions
  ansible.builtin.import_tasks: backup.yml
