---
- name: Install qemu-guest-agent package
  become: true
  apt: 
    pkg: qemu-guest-agent
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  notify: Start qemu-guest-agent
