---
# Creates a new database in the installed mariadb instance.
#
# collation: Collation mode (sorting). This only applies to new table/databases and does not update existing ones. [""]
# encoding: Encoding mode to use (e.g. utf8 or latin1_swedish_ci) at creation of database, dump or importation of sql script. [""]
# name: Name of the database
# state: Desired state of the database ('present' or 'absent')

- name: Verify inputs are valid
  ansible.builtin.assert:
    that:
      - name is defined
      - state == 'absent' or state == 'present'

- name: "Manage database: {{ name }}"
  community.mysql.mysql_db:
    collation: "{{ collation | default(omit) }}"
    encoding: "{{ encoding | default(omit) }}"
    name: "{{ name }}"
    state: "{{ state }}"
