---
- name: Install mariadb server
  tags: [mariadb_install]
  ansible.builtin.import_tasks: install.yml

- name: Configure mariadb server
  tags: [mariadb_configure]
  ansible.builtin.import_tasks: configure.yml
