---
- name: Configure nextcloud server
  gather_facts: true
  hosts: nextcloud_servers
  roles:
    - role: sudo
    - role: users
    - role: sshd
    - role: mariadb
      vars:
        mariadb_databases:
          - collation: "{{ nextcloud_db_collation }}"
            encoding: "{{ nextcloud_db_encoding }}"
            name: "{{ nextcloud_db_name }}"
        mariadb_root_password: "{{ nextcloud_db_root_password }}"
        mariadb_users:
          - name: "{{ nextcloud_db_user }}"
            password: "{{ nextcloud_db_password }}"
            privileges: "{{ nextcloud_db_name }}.*:ALL"
    - nextcloud
    - role: apache
      vars:
        apache_modules:
          - name: dir
          - name: env
          - name: headers
          - name: mime
          - name: rewrite
        apache_sites:
          - name: nextcloud
            template: nextcloud.conf.j2
    - role: php
