---
# install server
- name: Install xvfb package
  become: true
  apt: 
    pkg:
      - xvfb
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
- name: Add the server user
  ansible.builtin.user:
    name: '{{ vrising_server_username }}'
    password_lock: yes
- name: Ensure '{{ vrising_server_dir }}' exists
  file: 
    group: '{{ vrising_server_username }}'
    mode: '0700'
    owner: '{{ vrising_server_username }}'
    path: '{{ vrising_server_dir }}'
    state: directory
- name: Install v-rising server
  become: true
  become_user: '{{ vrising_server_username }}'
  ansible.builtin.shell: |
    /usr/games/steamcmd +force_install_dir "{{ vrising_server_dir }}" +login anonymous +app_update {{ vrising_server_appid }} +quit
  args:
    creates: '{{ vrising_server_dir }}/VRisingServer.exe'

# create log destination
- name: Ensure '{{ vrising_server_log_dir }}' exists
  file: 
    group: '{{ vrising_server_username }}'
    mode: '0755'
    owner: '{{ vrising_server_username }}'
    path: '{{ vrising_server_log_dir }}'
    state: directory
- name: Create logrotate entry for VRising server.log
  template: src=templates/etc/logrotate.d/VRising.j2 dest=/etc/logrotate.d/VRising owner=root group=root mode=0644

# configure server
- name: Ensure '{{ vrising_server_settings_dir }}' exists
  file: 
    group: '{{ vrising_server_username }}'
    mode: '0700'
    owner: '{{ vrising_server_username }}'
    path: '{{ vrising_server_settings_dir }}'
    state: directory
- name: Copy server configuration
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ vrising_server_settings_dir }}'
    owner: '{{ vrising_server_username }}'
    group: '{{ vrising_server_username }}'
    mode: '0644'
  notify: Restart VRising
  with_fileglob:
    - '{{ playbook_dir }}/roles/{{ role_name }}/files/Settings/*'
- name: Copy templated server configuration
  ansible.builtin.template:
    src: '{{ playbook_dir }}/roles/{{ role_name }}/templates/Settings/ServerHostSettings.json.j2'
    dest: '{{ vrising_server_settings_dir }}/ServerHostSettings.json'
    owner: '{{ vrising_server_username }}'
    group: '{{ vrising_server_username }}'
    mode: '0644'
  notify: Restart VRising

# configure server startup
- name: Copy startup script
  ansible.builtin.template:
    src: '{{ playbook_dir }}/roles/{{ role_name }}/templates/~/server/run-server.sh.j2'
    dest: '{{ vrising_server_dir }}/run-server.sh'
    owner: '{{ vrising_server_username }}'
    group: '{{ vrising_server_username }}'
    mode: '0754'
  notify: Restart VRising
- name: Create system service
  ansible.builtin.template:
    dest: /etc/systemd/system/VRising.service
    group: root
    mode: '0644'
    owner: root
    src: '{{ playbook_dir }}/roles/{{ role_name }}/templates/etc/systemd/system/VRising.service.j2'
  notify: Restart VRising

# create utility scripts
- name: Copy update script
  ansible.builtin.template:
    src: '{{ playbook_dir }}/roles/{{ role_name }}/templates/~/server/update-server.sh.j2'
    dest: '{{ vrising_server_dir }}/update-server.sh'
    owner: '{{ vrising_server_username }}'
    group: '{{ vrising_server_username }}'
    mode: '0754'