---
- name: Install xvfb package
  become: true
  apt: 
    pkg:
      - xvfb
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
- name: Add the server user
  ansible.builtin.user:
    name: '{{ vrising_server_username }}'
    password_lock: yes
- name: Ensure '{{ vrising_server_dir }}' exists
  file: 
    group: '{{ vrising_server_username }}'
    mode: '0700'
    owner: '{{ vrising_server_username }}'
    path: '{{ vrising_server_dir }}'
    state: directory
- name: Install v-rising server
  become: true
  become_user: '{{ vrising_server_username }}'
  ansible.builtin.shell: |
    /usr/games/steamcmd +force_install_dir "{{ vrising_server_dir }}" +login anonymous +app_update {{ vrising_server_appid }} +quit
  args:
    creates: '{{ vrising_server_dir }}/VRisingServer.exe'
- name: Ensure '{{ vrising_settings_dir }}' exists
  file: 
    group: '{{ vrising_server_username }}'
    mode: '0700'
    owner: '{{ vrising_server_username }}'
    path: '{{ vrising_settings_dir }}'
    state: directory
- name: Copy server configuration
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ vrising_settings_dir }}'
    owner: '{{ vrising_server_username }}'
    group: '{{ vrising_server_username }}'
    mode: '0644'
  with_fileglob:
    - '{{ playbook_dir }}/roles/{{ role_name }}/files/~/server/save-data/Settings/*'
- name: Copy startup script
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/roles/{{ role_name }}/files/~/server/run-server.sh'
    dest: '{{ vrising_server_dir }}'
    owner: '{{ vrising_server_username }}'
    group: '{{ vrising_server_username }}'
    mode: '0754'
- name: Create system service
  ansible.builtin.template:
    dest: /etc/systemd/system/VRising.service
    group: root
    mode: '0644'
    owner: root
    src: '{{ playbook_dir }}/roles/{{ role_name }}/templates/etc/systemd/system/VRising.service.j2'
  notify: Restart VRising