---
- name: Add the server user
  ansible.builtin.user:
    name: '{{ vrising_server_username }}'
    password_lock: yes

- name: Ensure '{{ vrising_server_dir }}' exists
  file: 
    group: '{{ vrising_server_username }}'
    mode: '0700'
    owner: '{{ vrising_server_username }}'
    path: '{{ vrising_server_dir }}'
    state: directory
- name: Download and unarchive steam console client
  ansible.builtin.unarchive:
    dest: '{{ steamcmd_dir }}'
    group: '{{ vrising_server_username }}'
    mode: '0700'
    owner: '{{ vrising_server_username }}'
    remote_src: yes
    src: '{{ steamcmd_url }}'