---
- name: "Ensure group exists: {{ group }}"
  loop: "{{ user.groups | default([]) }}"
  loop_control:
    loop_var: group
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: "Create user account: {{ user.username }}"
  ansible.builtin.user:
    create_home: "{{ user.create_home | default(not (user.system | default(false))) }}"
    groups: "{{ user.groups | default(omit) }}"
    name: "{{ user.username }}"
    password: "!"
    shell: "{{ user.shell | default(user.system | default(false) | ternary('/bin/false', '/bin/bash')) }}"
    system: "{{ user.system | default(false) }}"
    uid: "{{ user.uid | default(omit) }}"
