---
- name: Ensure /etc/ansible directory exists
  file: 
    mode: '0700'
    owner: root
    group: root
    path: /etc/ansible
    state: directory
- name: Copy Ansible configuration files to host
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/ansible
    owner: root
    group: root
    mode: '0700'
  with_fileglob:
    - '{{ playbook_dir }}/roles/{{ role_name }}/files/etc/ansible/*'
- name: Copy script to run Ansible
  ansible.builtin.copy:
    src: '{{ playbook_dir }}/roles/{{ role_name }}/files/usr/local/bin/run-ansible'
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0744'

- name: Re-run Ansible {{ ansible_pull_schedule }} minutes
  ansible.builtin.cron:
    job: /usr/local/bin/run-ansible >>{{ ansible_pull_logfile }} 2>&1
    minute: '{{ ansible_pull_schedule }}'
    name: "run ansible"
    state: present
    user: '{{ ansible_pull_user }}'

- name: Create logrotate entry for ansible-pull.log
  template: src=templates/etc/logrotate.d/ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644