---
- name: Ensure /etc/ansible directory exists
  file: 
    mode: '0755'
    owner: root
    group: root
    path: /etc/ansible
    state: directory
- name: Copy Ansible configuration files to host
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/ansible
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - '{{ playbook_dir }}/roles/{{ role_name }}/files/etc/ansible/*'
- name: Copy scripts to run Ansible
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0744'
  with_fileglob:
    - '{{ playbook_dir }}/roles/{{ role_name }}/files/usr/local/bin/*'

- name: Re-run Ansible bootstrap periodically
  ansible.builtin.cron:
    job: /usr/local/bin/cronjob-lock /usr/bin/ansible-pull --directory "/var/lib/ansible/local" --inventory "$(hostname)," --sleep 30 --url https://github.com/skleinjung/ansible.git --tags bootstrap configure-host.yml >>{{ ansible_pull_logfile }} 2>&1
    minute: '*/10'
    name: "run ansible bootstrap"
    state: present
    user: '{{ ansible_pull_user }}'
- name: Re-run Ansible every {{ ansible_pull_schedule }} minutes
  ansible.builtin.cron:
    job: /usr/local/bin/cronjob-lock /usr/bin/ansible-pull --directory "/var/lib/ansible/local" --sleep 5 --url https://github.com/skleinjung/ansible.git --vault-password-file /root/.vault-secret --skip-tags bootstrap,daily configure-host.yml >>{{ ansible_pull_logfile }} 2>&1
    minute: '{{ ansible_pull_schedule }}'
    name: "run ansible"
    state: present
    user: '{{ ansible_pull_user }}'
- name: Re-run Ansible daily tasks
  ansible.builtin.cron:
    job: /usr/local/bin/cronjob-lock /usr/bin/ansible-pull --directory "/var/lib/ansible/local" --sleep 30 --url https://github.com/skleinjung/ansible.git --vault-password-file /root/.vault-secret --tags daily configure-host.yml >>{{ ansible_pull_logfile }} 2>&1
    hour: '3'
    name: "run ansible daily"
    state: present
    user: '{{ ansible_pull_user }}'

- name: Create logrotate entry for ansible-pull.log
  template: src=templates/etc/logrotate.d/ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644