---
- name: Re-run the configuration playbook every {{ ansible_pull_schedule }} minutes
  ansible.builtin.cron:
    job: ansible-pull -d {{ ansible_pull_workdir }} --only-if-changed --vault-password-file /root/.vault-secret --url "{{ ansible_pull_repository }}" "{{ ansible_pull_playbook }}" -i inventory.yml >>{{ ansible_pull_logfile }} 2>&1
    minute: '{{ ansible_pull_schedule }}'
    name: "run ansible"
    state: present
    user: '{{ ansible_pull_user }}'

- name: Create logrotate entry for ansible-pull.log
  template: src=templates/etc/logrotate.d/ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644