---
- name: Execute backup
  block:
    - name: Generate timestamp (YYYYMMDDTHHMMSS)
      ansible.builtin.set_fact:
        timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
    - name: Enable maintenance mode
      vars:
        nextcloud_maintenance_mode: true
      ansible.builtin.include_tasks:
        file: actions/set_maintenance_mode.yml
    - name: "Ensure backup directory exists: {{ __nextcloud_paths.backup + '/' + timestamp }}"
      ansible.builtin.file:
        group: root
        mode: "0700"
        owner: root
        path: "{{ __nextcloud_paths.backup }}/{{ timestamp }}"
        state: directory
    - name: Create database backup
      community.mysql.mysql_db:
        state: dump
        name: "{{ nextcloud_db.name }}"
        target: "{{ __nextcloud_paths.backup }}/{{ timestamp }}/db.sql.gz"
    - name: "Create backup archive of data directory: {{ __nextcloud_paths.data }}"
      community.general.archive:
        dest: "{{ __nextcloud_paths.backup }}/{{ timestamp }}/nextcloud_data.tar.xz"
        format: xz
        group: root
        mode: "0640"
        owner: root
        path: "{{ __nextcloud_paths.data }}"
    - name: Disable maintenance mode
      vars:
        nextcloud_maintenance_mode: false
      ansible.builtin.include_tasks:
        file: actions/set_maintenance_mode.yml
