---
- name: Execute backup
  block:
    - name: Generate timestamp (YYYYMMDDTHHMMSS)
      ansible.builtin.set_fact:
        timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
    - name: Enable maintenance mode
      vars:
        nextcloud_maintenance_mode: true
      ansible.builtin.include_tasks:
        file: actions/set_maintenance_mode.yml
    - name: "Ensure backup directory exists: {{ __nextcloud_paths.backup + '/' + timestamp }}"
      ansible.builtin.file:
        group: "{{ nextcloud_backup_group }}"
        mode: "0750"
        owner: "{{ nextcloud_backup_user }}"
        path: "{{ __nextcloud_paths.backup }}/{{ timestamp }}"
        state: directory
    - name: Create database backup
      community.mysql.mysql_db:
        name: "{{ nextcloud_db.name }}"
        state: dump
        target: "{{ __nextcloud_paths.backup }}/{{ timestamp }}/db.sql.gz"
    - name: Set owner of database backup
      ansible.builtin.file:
        group: "{{ nextcloud_backup_group }}"
        mode: "0640"
        owner: "{{ nextcloud_backup_user }}"
        path: "{{ __nextcloud_paths.backup }}/{{ timestamp }}/db.sql.gz"
        state: file
    - name: "Create backup archive of data directory: {{ __nextcloud_paths.data }}"
      community.general.archive:
        dest: "{{ __nextcloud_paths.backup }}/{{ timestamp }}/nextcloud_data.tar.gz"
        format: gz
        group: "{{ nextcloud_backup_group }}"
        mode: "0640"
        owner: "{{ nextcloud_backup_user }}"
        path: "{{ __nextcloud_paths.data }}"
  always:
    - name: Disable maintenance mode
      vars:
        nextcloud_maintenance_mode: false
      ansible.builtin.include_tasks:
        file: actions/set_maintenance_mode.yml
