---
- name: Execute restore from backup
  block:
    - name: Assert path of backup to restore is specified
      ansible.builtin.assert:
        that:
          - nextcloud_restore_path is defined
    - name: Generate timestamp (YYYYMMDDTHHMMSS)
      ansible.builtin.set_fact:
        timestamp: "{{ ansible_date_time.iso8601_basic_short }}"
    - name: Delete existing database
      community.mysql.mysql_db:
        name: "{{ nextcloud_db.name }}"
        state: absent
    - name: Restore database backup
      community.mysql.mysql_db:
        collation: "{{ __nextcloud_db_collation }}"
        encoding: "{{ __nextcloud_db_encoding }}"
        name: "{{ nextcloud_db.name }}"
        state: import
        target: "{{ nextcloud_restore_path }}/db.sql.gz"
    - name: Remove existing data directory
      ansible.builtin.file:
        path: "{{ __nextcloud_paths.data }}"
        state: absent
    - name: Recreate data directory with correct permissions
      ansible.builtin.file:
        group: www-data
        mode: "0750"
        owner: root
        path: "{{ __nextcloud_paths.data }}"
        state: directory
    - name: Unarchive backup to data directory
      ansible.builtin.unarchive:
        copy: false
        dest: "{{ __nextcloud_paths.data }}"
        extra_opts: "--strip-components=1"
        src: "{{ nextcloud_restore_path }}/nextcloud_data.tar.xz"
    - name: Disable maintenance mode
      vars:
        nextcloud_maintenance_mode: false
      ansible.builtin.include_tasks:
        file: actions/set_maintenance_mode.yml
