# install Zettlr
- name: Install the .deb package
  apt:
    deb: "{{ zettlr_download_url }}"
# copy config
- name: Copy config
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/sean/.config/Zettlr/
    owner: sean
    group: sean
    mode: '0664'
  with_fileglob:
    - 'config/*'
# copy snippets
- name: Copy snippets
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /home/sean/.config/Zettlr/snippets
    owner: sean
    group: sean
    mode: '0664'
  with_fileglob:
    - 'snippets/*'