#!/usr/bin/env sh
chmod 600 ~/.vault-secret

apt-get update
apt-get install --no-install-recommends -y \
  software-properties-common

apt-add-repository --yes ppa:ansible/ansible
apt-get update

apt-get install --no-install-recommends -y \
  ansible \
  git

ansible-galaxy collection install ansible.posix
ansible-galaxy collection install community.general

# install cronjob
ansible-pull \
  --accept-host-key \
  --inventory "$(hostname)," \
  --purge \
  --tags bootstrap \
  --url https://github.com/skleinjung/ansible.git \
  --vault-password-file ~/.vault-secret \
  playbooks/configure-host.yml

# perform initial run
ansible-pull \
  --limit "$(hostname)" \
  --purge \
  --skip-tags bootstrap \
  --url https://github.com/skleinjung/ansible.git \
  --vault-password-file ~/.vault-secret \
  playbooks/install-dependencies.yml \
  playbooks/configure-host.yml