---
- name: Install common utilities
  apt: 
    pkg: 
      - apt-transport-https
      - curl      
      - software-properties-common
      - wget
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"