# apache_modules: List of Apache modules to manage. [None]
# apache_modules[].name: Name of the module.
# apache_modules[].state: Desired state of the site ('absent', 'disabled', or 'enabled'. [Enabled]
apache_modules: []

# apache_sites: List of sites to manage. [None]
# apache_sites[].name: Name of the site. Controls config file name and id used for apache control commands.
# apache_sites[].template: Path to the configuration template file. May be absolute or relative to Ansible template search path.
apache_sites: []

# apache2_version: Version string for the apache2 package to install. May contain wildcards. [2.4*]
apache2_version: 2.4*
