---
- name: "Install dependencies"
  tags: [nfs_client, install, nfs_client_install]
  when: wip_experimental_nfs_client_enabled
  block:
    - name: "Install nfs-common"
      ansible.builtin.apt:
        name: nfs-common
        state: present

- name: "Mount nfs shares"
  tags: [nfs_client, configure, nfs_client_configure]
  when: nfs_client_enabled
  block:
    - name: "Add nfs mounts"
      loop: "{{ nfs_client_mounts }}"
      ansible.builtin.include_tasks: _mount_nfs_share.yml
