---
- name: Check mandatory variables are defined
  assert:
    that:
      - desktop_username is defined
      - radeon_profile_config_dir is defined

- name: Add radeon-profile apt repository
  ansible.builtin.apt_repository:
    repo: ppa:radeon-profile/stable
    state: present
- name: Update repositories cache and install "radeon-profile" package
  apt:
   name: radeon-profile
   state: present
   update_cache: yes
   cache_valid_time: "{{ aptcachetime }}"

- name: Ensure '{{ radeon_profile_config_dir }}' exists
  file: 
    mode: '0775'
    owner: '{{ desktop_username }}'
    group: '{{ desktop_username }}'
    path: '{{ radeon_profile_config_dir }}'
    state: directory
- name: Copy radeon-profile configuration
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ radeon_profile_config_dir }}'
    owner: '{{ desktop_username }}'
    group: '{{ desktop_username }}'
    mode: '0664'
  with_fileglob:
    - '{{ playbook_dir }}/roles/{{ role_name }}/files/~/.config/radeon-profile/*'