---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu
    command: "/lib/systemd/systemd"
    image: docker.io/eniocarboni/docker-ubuntu-systemd:22.04
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../common/converge.yml
    prepare: ../common/prepare.yml
verifier:
  name: ansible
