# Probably should use these roles: https://github.com/sys0dm1n/ansible-ubuntu-desktop
# Visual Studio Code role from: https://github.com/gantsign/ansible-role-visual-studio-code

- hosts: all
  become: true
  tasks:
    - name: Update package lists
      tags: daily
      ansible.builtin.apt:
        cache_valid_time: "{{ aptcachetime }}"
        update_cache: true
    - name: Upgrade all packages
      tags: daily
      ansible.builtin.apt:
        name: "*"
        state: latest
        only_upgrade: true

- hosts: nas_servers
  become: true
  roles:
    - nfs-server

- hosts: qemu
  become: true
  roles:
    - role: qemu-agent

- hosts: vrising_servers
  become: true
  roles:
    - role: vrising-server

- name: Include plays for user workstations
  ansible.builtin.import_playbook: workstation.yml

- name: Include plays for Logitech Media Servers
  ansible.builtin.import_playbook: logitech_media_server/logitech_media_server.yml

- name: Include plays for nextcloud servers
  ansible.builtin.import_playbook: nextcloud/nextcloud_server.yml
