# Probably should use these roles: https://github.com/sys0dm1n/ansible-ubuntu-desktop
# Visual Studio Code role from: https://github.com/gantsign/ansible-role-visual-studio-code

- hosts: localhost
  become: true
  tags: bootstrap
  roles:
    - role: ansible-pull

- hosts: all
  become: true
  tasks:
    - name: Upgrade all packages
      tags: daily
      apt:
        cache_valid_time: 3600
        name: "*"
        state: latest
        update_cache: true
        update_only: true

- hosts: nas_servers
  become: true
  roles:
    - nfs-server

- hosts: qemu
  become: true
  roles:
    - role: qemu-agent

- hosts: vrising_servers
  become: true
  roles:
    - role: vrising-server

- name: Include plays for user workstations
  ansible.builtin.import_playbook: workstation.yml

- name: Include plays for nextcloud servers
  ansible.builtin.import_playbook: nextcloud_server.yml
