# Probably should use these roles: https://github.com/sys0dm1n/ansible-ubuntu-desktop
# Visual Studio Code role from: https://github.com/gantsign/ansible-role-visual-studio-code

- hosts: nas_servers
  become: true
  roles:
    - nfs-server

- hosts: qemu
  become: true
  roles:
    - role: qemu-agent

- hosts: vrising_servers
  become: true
  roles:
    - role: vrising-server

- name: Include plays for coder servers
  ansible.builtin.import_playbook: coder/coder_server.yml

- name: Include plays for user workstations
  ansible.builtin.import_playbook: workstation.yml

- name: Include plays for Logitech Media Servers
  ansible.builtin.import_playbook: logitech_media_server/logitech_media_server.yml

- name: Include plays for nextcloud servers
  ansible.builtin.import_playbook: nextcloud/nextcloud_server.yml

- name: Update system packages
  become: true
  hosts: all
  tags:
    - daily
  tasks:
    - name: Update package lists and upgrade all packages
      ansible.builtin.apt:
        cache_valid_time: "{{ aptcachetime }}"
        update_cache: true
        upgrade: true
    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot the machine if needed
      ansible.builtin.shell: sleep 15 && /sbin/shutdown -r now 'Rebooting to apply package updates'
      changed_when: true
      ignore_errors: true
      when: reboot_required.stat.exists
