---
- hosts: all
  name: Install requirements from ansible-galaxy
  tasks:
    - name: Install requirements
      tags: [always]
      ansible.builtin.command: ansible-galaxy install -r '{{ playbook_dir }}/../requirements.yml'
