---
# install Shopify CLI
- name: Install shopify cli dependencies
  apt:
    pkg: 
      - ruby-dev
      - libltdl-dev
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
- name: Install the Shopify .deb package
  apt:
    deb: "{{ shopify_cli_url }}"