---
aptcachetime: 3600

# NFS options
# must be enabled via wip_experimental_nfs_client_enabled for this setting to take effect
nfs_client_mounts:
  - host: 192.168.68.10
    name: /srv/nfs/usb
    opts: auto,nodev,noexec,nosuid,rw
    path: /mnt/usb
    state: mounted

# sshd options
# note: sshd is disabled by default, so these options are only applied if sshd_enabled is overridden elsewhere
sshd_users:
  - authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOT7hR5cbwyrOfcEdjhrepLec8CBsfaPQexbotN+hUoz Sean Kleinjung
    username: sean

# users configuration
users_config:
  - groups:
      - adm
      - sudo
    uid: 60000
    username: sean
