---
# apache options
apache2_version: 2.4*

# mariadb options
mariadb_data_directory: /var/lib/nextcloud/db/data
mariadb_version: 1:10.6*

# php options
php_version: 2:8.1*

# ssh options
sshd_enabled: 'true'