---
- name: Check mandatory variables are defined
  assert:
    that:
      - desktop_username is defined

- name: Ensure /home/{{ desktop_username }}/.ssh directory exists
  file: 
    group: '{{ desktop_username }}'
    mode: '0700'
    owner: '{{ desktop_username }}'
    path: /home/{{ desktop_username }}/.ssh
    state: directory

- name: Update repositories cache and install "openssh-server" package
  apt:
    name: openssh-server
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
- name: Add authorized ssh keys
  ansible.builtin.copy:
    dest: /home/{{ desktop_username }}/.ssh/authorized_keys
    group: '{{ desktop_username }}'
    mode: '0644'
    owner: '{{ desktop_username }}'
    src: '{{ playbook_dir }}/roles/{{ role_name }}/files/authorized_keys'

- name: Configure sshd
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    group: root
    mode: '0644'
    owner: root
    src: '{{ playbook_dir }}/roles/{{ role_name }}/files/sshd_config'
  notify: Restart sshd
