---
- name: Check mandatory variables are defined
  assert:
    that:
      - username is defined

- name: Ensure /home/{{ username }}/.ssh directory exists
  file: 
    group: '{{ username }}'
    mode: '0700'
    owner: '{{ username }}'
    path: /home/{{ username }}/.ssh
    state: directory

- name: Update repositories cache and install "openssh-server" package
  apt:
    name: openssh-server
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
- name: Add authorized ssh keys
  ansible.builtin.copy:
    dest: /home/{{ username }}/.ssh/authorized_keys
    group: '{{ username }}'
    mode: '0644'
    owner: '{{ username }}'
    src: 'authorized_keys'

- name: Configure sshd
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    group: root
    mode: '0644'
    owner: root
    src: 'sshd_config'
  notify: Restart sshd
